### ISSUE TITLE
Debugger UI looks weird/unreadable in kubuntu dark theme

### ISSUE THREAD

**Issue by nzeemin** [nzeemin/ukncbtl-qt#2]
![Screenshot_20200430_220955](https://user-images.githubusercontent.com/10085275/80749624-62785b00-8b2f-11ea-8800-5c23ff2b9064.png)

**Comment by nzeemin** [comment]
![Screenshot_20200430_220955](https://user-images.githubusercontent.com/10085275/85904371-374d7780-b811-11ea-997e-746a7639a9d5.png)

**Comment by nzeemin** [comment]
Not an ideal solution but most text visible at least.
![Screenshot_20200627_005926](https://user-images.githubusercontent.com/10085275/85904479-83002100-b811-11ea-98f0-262ae6d3916f.png)

**Comment by aberranthacker** [comment]
Awesome! Thank you very much!

**Comment by nzeemin** [comment]
I think we have a good implementation now:

![Screenshot_20230723_190720](https://github.com/nzeemin/ukncbtl-qt/assets/10085275/655fb72b-51e2-4175-9907-cbd6da6d114b)
