### ISSUE TITLE
Screen colors look wierd when you use non-default palette.

### ISSUE THREAD

**Issue by aberranthacker** [nzeemin/ukncbtl-qt#3]
Something breaks when you switch to a non-default palette.
In the screenshot below palette 5 is used. 
![title](https://user-images.githubusercontent.com/2966983/85940329-4e30be80-b924-11ea-98d4-2d07539451d4.png)
Here I switch to palette 3 in the middle of the screen, and to palette 5 in the bottom part.
![menu](https://user-images.githubusercontent.com/2966983/85940335-54bf3600-b924-11ea-8f8f-9fc3208656b4.png)
And here is how the title screen suppose to look
![expected_title](https://user-images.githubusercontent.com/2966983/85940698-9e108500-b926-11ea-81d5-442313a4ecb5.png)

**Comment by nzeemin** [comment]
@aberranthacker Could you please attach a state file saved from the emulator?
Also does it works well in the Win32 version of the emulator? - I could check it by myself with a state file.

**Comment by aberranthacker** [comment]
Here is the saved state: [broken_palette.zip](https://github.com/nzeemin/ukncbtl-qt/files/4842545/broken_palette.zip)
Win32 works well. In fact, the last screenshot is taken by the Win32 version. (RGB colors)

**Comment by nzeemin** [comment]
![image](https://user-images.githubusercontent.com/10085275/86186017-962c2d00-bb40-11ea-8f7e-dcc53cf38a10.png)
