### ISSUE TITLE
Debugging area is not maximized on start of the emulator.

### ISSUE THREAD

**Issue by aberranthacker** [nzeemin/ukncbtl-qt#6]
![Screenshot_20200628_101401_with_drawings](https://user-images.githubusercontent.com/2966983/85942060-8db0d800-b92f-11ea-846e-a19d10f83a01.png)
It would be really great if emulator would start like this: :smiley: 
![Screenshot_20200628_111210](https://user-images.githubusercontent.com/2966983/85942179-5e4e9b00-b930-11ea-9f3a-7e463987b555.png)

**Comment by aberranthacker** [comment]
I forgot to mention that my screen resolution is 1366x768. Maybe the screen layout breaks when you use relatively low resolutions.

**Comment by nzeemin** [comment]
That was a bug in restoring geometry/state of the central widget. Applied a hack, tested under Windows and Kubuntu, looks fine now.
